### ISSUE TITLE
`nullspace` does not return `∅` for single column non-zero matrix

### ISSUE THREAD

**Issue by JeffFessler** [JuliaLang/LinearAlgebra.jl#1014]
Julia 1.9.2:

```julia
using LinearAlgebra
nullspace(ones(3,1))
```
the output is `1×0 Matrix{Float64}` suggesting that the null space is empty.
(EDIT - I removed the embarrassingly wrong stuff here...)

btw, sadly the blue links to "source" code in the docs have disappeared in the julia manual for the LinearAlgebra functions, e.g.,
https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.nullspace

**Comment by stevengj** [comment]
The current behavior is correct, I believe.

The `nullspace` function returns a *basis* for the nullspace.   When the nullspace is 0-dimensional, consisting only of the zero vector, then the correct basis is indeed the empty basis (since the empty sum is zero).  That is the case here.

See e.g. [this explanation (Wikipedia)](https://en.wikipedia.org/wiki/Examples_of_vector_spaces#Trivial_or_zero_vector_space) or [this explanation (mathstackexchange)](https://math.stackexchange.com/questions/1909645/empty-set-is-the-only-basis-of-the-zero-vector-space-0).

**Comment by JeffFessler** [comment]
I apologize for this embarrassing error on my part.
This came up because a student asked about a related topic and I reminded to the student that a basis cannot have any zero vectors in it.  Then I foolishly made the same mistake here!
I think what threw me is the `1×0 Matrix` output which did not seem synonymous with the empty set.  I was expecting Julia to return `∅`.  I edited the title just so that the issue looks less dumb.  😅 
I am not proposing to reopen the issue.  Returning an empty `1x0` matrix is fine.  Thanks!
