### ISSUE TITLE
Missing matrix product method

### ISSUE THREAD

**Issue by cossio** [JuliaLang/LinearAlgebra.jl#13]
```
julia> qr(randn(10,3)).Q * svd(randn(3,3)).V
# ERROR: DimensionMismatch: first dimensions of C, 3, and V, 10 must match
```

but,

```
julia> qr(randn(10,3)).Q * Matrix(svd(randn(3,3)).V)
```

works. The first version should also work. There should be no need to instantiate a `Matrix` (as in the second example). It seems that there is a missing method for `*` here?

**Comment by dkarrasch** [comment]
Please, consider the following hints to make it easier for others.

1. Provide the full stacktrace: This makes it clearer where to search for potential errors. For instance, the `DimensionMismatch` error indicates that it's not a missing method, but a too strict dimension check.
2. Provide Julia's version number: in this case, the issue seems already resolved in v1.10.

Finally, `LinearAlgebra.jl` has not been excised yet, so issues need to be reported over at Julia Base.
