### ISSUE TITLE
scalar multiplication with triangular matrix is wrong

### ISSUE THREAD

**Issue by tomhaber** [JuliaLang/LinearAlgebra.jl#139]
The multiplication of a triangular matrix with a scalar value is wrongly implemented in triangular.jl, lines 155-172

The lines
for i = UpLo == :L ? j:n : 1:j
should say
for i = UpLo == :U ? j:n : 1:j

The method should probably also work on a copy of A instead of manipulating A itself

Regards,
Tom

**Comment by pao** [comment]
@JuliaBackports

**Comment by pao** [comment]
(that's the most action I've seen on a single issue in one minute)

**Comment by andreasnoack** [comment]
The ranges were actually correct, but they got parsed wrongly because of the `? :`. Hence, the fix was

```
i = UpLo == :L ? (j:n) : (1:j)`
```

but you were right that a copy was missing. Thanks again for the report.

**Comment by tomhaber** [comment]
Oh right, I totally misread the loops. Is there a performance difference between rows or columns first?

**Comment by andreasnoack** [comment]
I have backported (@JuliaBackports) the fix for this. Should anything else be done to comply with the new backporting procedure?

**Comment by ivarne** [comment]
@StefanKarpinski will have to answer for that. I like the github label much better than the mailing list, because it gives a [nice place](https://github.com/JuliaLang/julia/issues?q=+label%3A%22backport+pending%22+) to check whether there are still issues/PRs that should be considered before tagging a 0.3.x minor release.

@tomhaber For large arrays, there is a huge difference between iterating row wise or column wise over an array. This is because memory is much slower than CPUs, so the CPU has a local copy that it works on. If you iterate in the "wrong" order, that copy needs to be reloaded.

**Comment by StefanKarpinski** [comment]
Jury's still out on the @JuliaBackports list. Not sure if it's a good idea yet or not.
