### ISSUE TITLE
BoundsError when multiplying non-square triangular matrices

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/LinearAlgebra.jl#143]
This is the same on 0.3.1 and latest `master`:

``` julia
julia> A = randn(4,5)
4x5 Array{Float64,2}:
 -0.700702  -0.211578   -0.317317  -1.12736   -0.248566
  0.478831  -0.0771078  -0.757577   0.302632  -0.618207
 -0.405469   0.441741   -0.532182   1.19353    0.514175
 -0.870518  -0.963187    0.584838   1.69081    0.617973

julia> Q, R = qr(A);

julia> R
4x5 Array{Float64,2}:
 1.28159  0.601355  -0.338435  -0.796639   -0.677506
 0.0      0.901081  -0.520844  -0.451767    0.154915
 0.0      0.0        0.956059  -0.0238198   0.508743
 0.0      0.0        0.0        2.19239     0.590254

julia> R_tri = Triangular(R, :U)
4x5 Triangular{Float64,Array{Float64,2},:U,false}:
 1.28159  0.601355  -0.338435  -0.796639   -0.677506
 0.0      0.901081  -0.520844  -0.451767    0.154915
 0.0      0.0        0.956059  -0.0238198   0.508743
 0.0      0.0        0.0        2.19239     0.590254

julia> istriu(R)
true

julia> Q*R
4x5 Array{Float64,2}:
 -0.700702  -0.211578   -0.317317  -1.12736   -0.248566
  0.478831  -0.0771078  -0.757577   0.302632  -0.618207
 -0.405469   0.441741   -0.532182   1.19353    0.514175
 -0.870518  -0.963187    0.584838   1.69081    0.617973

julia> Q*R_tri
ERROR: BoundsError()
 in copy! at array.jl:52
 in convert at linalg/triangular.jl:104
 in * at linalg/triangular.jl:210
```

**Comment by staticfloat** [comment]
Looks like subtraction is also affected:

``` julia
julia> R_tri - R
ERROR: BoundsError()
 in copy! at array.jl:52
 in convert at linalg/triangular.jl:104
 in - at linalg/special.jl:89
```

**Comment by wkearn** [comment]
This happens because of the following lines in `triangular.jl`

``` julia
function convert{Tret,T,S,UpLo,IsUnit}(::Type{Matrix{Tret}}, A::Triangular{T,S,UpLo,IsUnit})
    B = Array(Tret, size(A, 1), size(A, 1))
    copy!(B, A.data)
    ...
end
```

It creates a new square matrix using only the size of the first dimension of the triangular matrix (because it assumes that the triangular matrix is square). Then when it tries to copy the triangular matrix into `B`, `B` is too small and you get a `BoundsError()`.

An easy enough fix -- just change it to `B = Array(Tret,size(A,1),size(A,2))` -- but shouldn't triangular matrices always be square? We certainly seem to make that assumption here and elsewhere in the linear algebra code. For instance:

``` julia
julia> similar(R_tri)
ERROR: ArgumentError("a Triangular matrix must be square")
 in similar at linalg/triangular.jl:130
 in similar at abstractarray.jl:115
```

**Comment by andreasnoack** [comment]
The `Triangular` type is meant to be square so we should probably check that in the constructor. I have thought about extending the type to non-square matrices mainly because of the reason that @staticfloat mentions, i.e. QR on wide matrices. However, the main reason to dispatch on `Triangular` is forward and back solve which require that the matrix is square. Furthermore, it is not so obvious what a non-square triangular matrix is and in this case I'd actually call the matrix trapezoid. A `Trapezoid` type could actually be useful as there are specialized routines for them.

**Comment by staticfloat** [comment]
I agree that it makes sense to distinguish between `Triangular` and `Trapezoidal`, but perhaps the first fix is to just add checks to `Triangular()` to ensure that the input is square?

**Comment by andreasnoack** [comment]
Indeed. I'll do that.

**Comment by staticfloat** [comment]
Thanks!  I'm actually writing a simple QR factorizer for a "High Performance Computing" class I'm taking right now, and so naturally I have taken it upon myself to write both MATLAB solutions as well as Julia solutions to prove to my professor that Julia is awesome.

I tried to use the `Triangular` type to force the subdiagonal of `R` to be completely zero instead of nearly zero (just for printing's sake) and discovered this little gem.  :)

**Comment by andreasnoack** [comment]
Ah. I was a bit surprised that you were doing QRs. Hopefully you'll succeed.

**Comment by staticfloat** [comment]
Thanks Andreas!  I'm no linear algebra whiz, but QR isn't too hard.  The only part that requires some consideration is when you're dealing with non-square inputs. :)
