### ISSUE TITLE
eig(Hermitian(A)) does not work

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/LinearAlgebra.jl#1510]
I wonder if methods like `eig` should be more general and not only for StridedMatrix. Currently, `eigvals` works for `Hermitian(A)`, but `eig` does not.

Cc: @andreasnoackjensen

**Comment by andreasnoack** [comment]
Actually I wondered about the same thing when I wrote the wrappers for the generalized eigen solvers because I wanted `eigvals` to work for `Hermitian` and therefore ended up defining `eigvals(A::AbstractMatrix, B::AbstractMatrix)`. I think we should do the same thing for all the MATLAB compatible functions.

**Comment by ViralBShah** [comment]
Agree - that is why I filed this issue, rather than just fixing `eig`. It needs to be done systematically across all the compatible functions.

**Comment by andreasnoack** [comment]
I think this one can be closed now

**Comment by ViralBShah** [comment]
Closed in f92fd854d2c35eab59019c18aea06ab646637cb2
