### ISSUE TITLE
Matrix exponentiation

### ISSUE THREAD

**Issue by asbidyarthy** [JuliaLang/LinearAlgebra.jl#1514]
```
# We used the formula for expm in julia,

# Compute all eigenvectors and eigenvalues
(d,V)= eig(A)
D=diagm(d)
expm(A)= V * diagm(exp(diag(D)) / V;
```

It gives the correct answer for symmetric A in julia.
It does not work for asymmetric A in julia
(gives no method for / Array{Complex128,2},Array{Complex128,2} in base.jl:60)
-- the same however works in matlab.

The function is about 4.45 times slower than matlab library expm
for 100x100 matrices and 2.9 times slower than matlab library
expm for 1000x1000 matrices.

**Comment by timholy** [comment]
There's a bit of time-savings to be had by changing your division to a multiplication by the transpose:

julia> A = randn(1000,1000); A = A + A';

julia> function expmslow(A)
         (d,V) = eig(A)
         return V \* diagm(exp(d)) / V
       end

julia> function expm(A)
         (d,V) = eig(A)
         return V \* diagm(exp(d)) \* V'
       end

julia> @time eAslow = expmslow(A);
elapsed time: 3.946049928665161 seconds

julia> @time eAslow = expmslow(A);
elapsed time: 3.3887288570404053 seconds

julia> @time eA = expm(A);
elapsed time: 3.306368112564087 seconds

julia> @time eA = expm(A);
elapsed time: 3.276883125305176 seconds

But it's not enough to close the gap.

**Comment by pao** [comment]
Isn't this kind of JuliaLang/LinearAlgebra.jl#1515? Let's keep `expm()` talk all together.

**Comment by StefanKarpinski** [comment]
I'm leaving the issue closed since it's not a Julia bug, but there are a couple of issues with this example code:
1. Doing `D = diagm(d)` then `diag(D)` is a lot of pointless work — you could just write `diagm(exp(d))`.
2. Isn't the formula `V*diagm(exp(d))/V` incorrect? I'm pretty sure the right formula is `V*diagm(exp(d))*V'` — which is also much faster (especially because we don't actually take the transpose at all in this case).

You could write this latter formula even more efficiently as

``` julia
diagmm(V,exp(d))*V'
```
