### ISSUE TITLE
Support StridedArrays with strides not supported by BLAS routines

### ISSUE THREAD

**Issue by samuela** [JuliaLang/LinearAlgebra.jl#155]
I'm getting "Intel MKL ERROR: Parameter 10 was incorrect on entry to DGEMM ." printed to stdout with no other indication of what went wrong.

**Comment by dmbates** [comment]
More context will be needed.  DGEMM performs multiplication of dense matrices.  Does that help you to narrow down where the error is occurring?  Also, it will help to have the output of 

versioninfo()

**Comment by jiahao** [comment]
Please post a minimal example of code that triggered this problem and the result of `versioninfo()`. Otherwise it is impossible to diagnose this issue other than to point you to the [signature of dgemm](http://www.math.utah.edu/software/lapack/lapack-blas/dgemm.html), where parameter 10 is LDB, the leading dimension of B in a A*B matrix product.

**Comment by samuela** [comment]
Yeah, I'm trying to track it down right now. I'll post as I figure it out.

**Comment by samuela** [comment]
```
julia> versioninfo()
Julia Version 0.3.4-pre+84
Commit b296937 (2014-12-22 13:18 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libmkl_rt
  LAPACK: libmkl_rt
  LIBM: libimf
  LLVM: libLLVM-3.3
```

**Comment by samuela** [comment]
Alright, this reproduces exactly the error:

``` julia
using ArrayViews

function moving_window(arr, n)
    shp = (size(arr, 1) * n, size(arr, 2) - n + 1)
    strided_view(arr, shp, ArrayViews.contrank(arr), strides(arr))
end

x = rand(5, 5)

rand(10, 4) * moving_window(x, 2)
```

**Comment by samuela** [comment]
Oops, that should be `rand(4, 10)` instead of `rand(10, 4)`.

**Comment by jiahao** [comment]
Thanks. I can reproduce the bug. Parameter 10 is calculated in `linalg/blas.jl:gemm!` as `max(1,stride(B,2)) = 5`, which is strange since `B` is a 10x4 matrix. The stride is probably being calculated incorrectly.

**Comment by samuela** [comment]
Well, I'm specifying a custom stride in `moving_window` which likely causes the confusion.

**Comment by samuela** [comment]
Can DGEMM even handle a matrix laid out in this way? I'm not familiar with BLAS.

**Comment by jiahao** [comment]
I'm not sure exactly what your code is supposed to do, but if you set

``` jl
julia> x=reshape(1.:25.,5,5)
5x5 Array{Float64,2}:
 1.0   6.0  11.0  16.0  21.0
 2.0   7.0  12.0  17.0  22.0
 3.0   8.0  13.0  18.0  23.0
 4.0   9.0  14.0  19.0  24.0
 5.0  10.0  15.0  20.0  25.0
```

then the `B` in `gemm!` is 

``` jl
[1.0 6.0 11.0 16.0
 2.0 7.0 12.0 17.0
 3.0 8.0 13.0 18.0
 4.0 9.0 14.0 19.0
 5.0 10.0 15.0 20.0
 6.0 11.0 16.0 21.0
 7.0 12.0 17.0 22.0
 8.0 13.0 18.0 23.0
 9.0 14.0 19.0 24.0
 10.0 15.0 20.0 25.0]
```

Is that the expected matrix?

**Comment by samuela** [comment]
Yup, exactly

**Comment by jiahao** [comment]
If the desired stride is indeed 5, then BLAS cannot handle this computation. The documentation linked to above states that the parameter `LDB` to `DGEMM` must be at least the common dimension (10 in this case).

I'm not really sure what to do here. Maybe we can insert a runtime check in `LinAlg.BLAS.gemm!` if the strides are what BLAS expects and fall back to `generic_matmul!` otherwise?
