### ISSUE TITLE
Warnings when working with singular matrices

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaLang/LinearAlgebra.jl#26]
Consider the following example taken from http://www.walkingrandomly.com/?p=5092:

```
A = [1 2 3;
     4 5 6;
     7 8 9];

b = [15, 15, 15]

x = A \ b
```

On my OS X build of master, this produces the solution: 

```
3-element Array{Float64,1}:
 -39.0
  63.0
 -24.0
```

which is valid, but could potentially have been quite inaccurate. As the linked blog post notes, Matlab offers a warning in this case that the condition number of `A` is very high and that the result may be inaccurate.

Julia should probably also raise warnings when solve operations are likely to produce inaccurate solutions.

**Comment by ViralBShah** [comment]
Does anyone know what logic matlab uses in such cases? @alanedelman @andreasnoackjensen ?

**Comment by johnmyleswhite** [comment]
If someone knows details, that would be great. It sounds like they may just check `cond(A)`.

**Comment by ViralBShah** [comment]
You certainly do not want to compute `cond(A)`. We should get `rcond` as part of the factorization. The question is, do we code in certain values as threshold or is there a better way to address this?

**Comment by andreasnoack** [comment]
I have a qualified guess for MATLAB's criterion:

``` MATLAB
>> diag([1,eps()])\ones(2,1);
>> diag([1,0.9999999*eps()])\ones(2,1);
Warning: Matrix is close to singular or badly scaled. Results may
be inaccurate. RCOND =  2.220446e-16. 
```

so if this is what we want, it would be easy to mimic that behaviour since the rcond estimate seems to match the 1-norm estimate from xgecon. Do we have a warning policy?

**Comment by StefanKarpinski** [comment]
I'm not a big fan of warnings like this – it's too easy for the programmer to ignore them or not see them at all, e.g. in deployed production code. (Ideally, we should have a system in place where warnings get logged correctly in deployed production systems so there's a chance that monitoring systems or someone looking through application logs will notice this kind of thing.) My suggestion in the [email thread](https://groups.google.com/forum/#!topic/julia-dev/R4MT77kfa_w) about this issue was that we can check if the result is actually close enough. @johnmyleswhite's counterpoint was that we may want to warn even when the user is close enough since they might think their code is fine because it happens to work, only to be bitten later on other values. The most conservative approach is to warn when the condition number is high but return the result anyway as long as it's close enough and raise an error when the condition number is high and the result isn't close enough. That would cause an application error and someone would have to investigate.

**Comment by johnmyleswhite** [comment]
I think it's reasonable to always return the value that's calculated rather than throw an error. I think warnings in all suspect cases are far more important than errors in extreme cases, especially for a language that's hoping to be adopted by R users. I agree that we need some generic facility that merges logging and interactive errors. But until we get there, it's worth keeping in mind that R isn't displacing other programming languages: it's displacing Stata, SPSS and other GUI programs that present thorough warnings to users who trust that any calculation that doesn't throw an error has produced a valid result. It shouldn't be possible to do obviously bad science in Julia without someone wagging a finger at you.

**Comment by StefanKarpinski** [comment]
We're not _just_ trying to replace R and Matlab here as interactive environments – we're also trying to make it possible to build reliable deployed systems in Julia. I also don't see how raising an error when the result of `c = A\b` doesn't have the defining property that `A*c` is close to `b` is problematic in interactive usage. Having that be an error instead of making me _check_ if the bad case occurred or not seems much friendlier.

**Comment by johnmyleswhite** [comment]
I'm not opposed to raising an error; I just don't see it as necessary, especially if it increases the cost of a procedure.

**Comment by ViralBShah** [comment]
@StefanKarpinski  I am not sure what it means "that the condition number is high and the result is not close enough". This is implicit. When the condition number is deemed too high, we should be signalling it. The question is how. Also, there are cases, when even if the matrix is close to singular, you still want the answer, because the error is in the right direction - like in the case of shift-invert eigs. Throwing an error is not a good idea, in my opinion. We could throw a `MatrixIllConditioned` exception, but then we can't return the result.

One alternative is to make `\` have good interactive behaviour, printing warnings and such. For non-interactive cases, it is not a good idea to use `\` in any case, and Factorization objects can have more sophisticated interfaces like returning error codes from LAPACK, the condition number, etc.

**Comment by ViralBShah** [comment]
@johnmyleswhite Although I have to check, I believe that we can compute the condition number at no extra cost. Typically, it is computed using Gaussian elimination anyways, and LAPACK may give it to us as a by-product.

**Comment by StefanKarpinski** [comment]
The point is that even when the condition number is high, the algorithm may return `c` such that `A*c` is close to `b`, in which case you "got lucky" even though the input was ill-conditioned. My argument is that in that case it's fine to return `c` and issue a warning that the condition number was high. If the algorithm produces a value `c` such that `A*c` is not close to `b` then the algorithm has essentially failed. My point is that in that case we should raise an error. This seems like it's the right behavior regardless of whether we're working interactively or non-interactively. I'm not sure what the point of having an incorrect result for `A\b` is – what are you going to do with some `c` that just happens to have been produced by this function but doesn't have the property that `A*c` is close to `b`? I'm failing to see how that's a useful value to have.

**Comment by andreasnoack** [comment]
@ViralBShah I think `xgecon` is exactly for that. A reframing of @StefanKarpinski's point could be to ask how Julia should handle rank deficient but consistent systems as the example @johnmyleswhite gives. We are treating square and non-square cases differently right now

```
julia> [1 2 3;4 5 6;7 8 9]\[15,15,15]
3-element Array{Float64,1}:
 -39.0
  63.0
 -24.0
julia> [1 2 3 0;4 5 6 0;7 8 9 0]\[15,15,15]
4-element Array{Float64,1}:
 -7.5        
 -9.32587e-15
  7.5        
  0.0   
```

Non-sqaure problems are solved by QR that can handle underdetermined systems and square problems are handled by LU. MATLAB gives a rank deficient warning in the non-square case so we might consider that as well. One solution could be to raise warnings when using `\(Matrix,VecOrMat)` but not when using `\(Factorization,VecOrMat)`. If warnings are raised in all cases, I would like an easy way to switch them off as I solve rankdeficient problems all the time.

**Comment by alanedelman** [comment]
The problem is that computing languages are not consisent.  I'm okay with the following principle for warnings:

Provide a warning if 
There's a known inexpensive metho relative to the rest of the computation performance wise 

rcond has certainly been a grand tradition in linear algebra

**Comment by jiahao** [comment]
The experimental branch `cjh/gesvx` provides some very simple wrappers around LAPACK `xgesvx` routines, which are general linear solvers with error estimates.

Some very simple testing appears to show that the overhead in calling `gesvx!` over `gesv!` is not very large.

<pre>
julia> N=10000;T=randn(N,N-1);A=T*T';b=randn(N);
julia> @elapsed Z=LAPACK.gesvx!(A, b)
WARNING: Matrix is singular to working precision.
33.743612314
julia> @elapsed Y=A\b
30.727691666
</pre>

Assuming this result holds in general, then it may be worth the performance penalty to replace `gesv!` with `gesvx!` in `\`, perhaps with an optional flag to call the former.

**Comment by jiahao** [comment]
From JuliaLang/julia#4594: Since the condition number estimator `LAPACK.gecon!` is already wrapped in `cond()`, an alternative (and probably simpler) thing to do would be to call `cond()` by default in `A\b` to check that the condition number is reasonable, throw a warning if it isn't, and possibly have an optional flag to turn off the `cond()` call.

**Comment by andreasnoack** [comment]
Continuing the discussion from https://github.com/JuliaLang/julia/commit/4bf31d868ce1a93b921dbb21032c3fff272a0ece#commitcomment-9597896 here since this issue is about exactly the topic of the discussion.

@jakebolewski, @jiahao and I talked about some options this afternoon. The conclusion so far is that it would be useful to be able to either turn off the warning or catch them as with exceptions, but at the same time allow a default behavior with warning because they can be very useful. In particular for non-experts of numerical linear algebra.

A problem is that `\` is very restricted in terms of possible arguments: because it is infix, it can really only take two arguments and it should return a matrix or vector of the result, e.g. a tuple with condition number or other auxiliary output would be very inconvenient.

One solution that we thought could accomplish this is that `\`, which we consider the default for use in the REPL or simple scripts, always warns when the condition number is above some threshold, but that `A_ldiv_B!` gets extended. Then `A_ldiv_B!` would serve as the "expert" method where more control is provided. It already has this kind of interpretation because it works on a preallocated output array.

Since `A_ldiv_B!` writes the solution to one of its arguments and isn't an infix operator, it can be much more flexible. It could therefore take an argument that controls the behavior when the problem matrix is ill conditioned, e.g. you could choose between something `:ignore`, `:warn` and `:throw`. The method is also free to return all kinds of information if we want it to do so. We could consider an option of error bounds of the solution or other auxiliary output.

**Comment by tkelman** [comment]
I don't know if this will necessarily have to be in `A_ldiv_B!` since the computational complexity of determining whether or not to warn (or calculate the quantity that the warning decision would need to be made from) could vary widely depending on the types of the arguments. I'm not sure if this can be done generically, it might be more appropriate to handle at an expert-driver lapack wrapper level.

**Comment by andreasnoack** [comment]
Some options might not be very generic, and are therefore better handled at the individual solver level, but I think the decision of whether to warn, throw or to remain silent could be considered generic.

**Comment by tkelman** [comment]
Sure, but it feels like `A_ldiv_B!` (or just `ldiv!` if we can simplify it down to that via transpose types) is maybe not the right API for adding this to. Particularly when you start getting into error bounds and other outputs.

**Comment by tkelman** [comment]
Bump. The logic on master is still wrong here and needs to be fixed while we determine a better API. `isinteractive` is the wrong thing to use for deciding whether or not to print warnings.

**Comment by Sacha0** [comment]
Unlikely to receive attention prior to 0.6. Best!

**Comment by c42f** [comment]
Now that JuliaLang/julia#24490 is merged, we have some more expressive options for generating warnings and capturing them.  Also for possibly turning them into exceptions with the right Logger installed, though I'm not yet sure that's a pattern which should be encouraged.

**Comment by inkydragon** [comment]
In Julia 1.6.3/1.7.0-rc1 `A \ b` just throw an error, and `ldiv!` gives a right answer. 
Can this issue be closed now?

```julia
julia> A = [1 2 3; 4 5 6; 7 8 9];

julia> b = [15, 15, 15.0];

julia> x = A \ b
ERROR: LinearAlgebra.SingularException(3)
Stacktrace:
 [1] checknonsingular
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\LinearAlgebra\src\factorization.jl:19 [inlined]
 [2] checknonsingular
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\LinearAlgebra\src\factorization.jl:21 [inlined]
 [3] #lu!#146
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\LinearAlgebra\src\lu.jl:82 [inlined]
 [4] #lu#153
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\LinearAlgebra\src\lu.jl:279 [inlined]
 [5] lu (repeats 2 times)
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\LinearAlgebra\src\lu.jl:278 [inlined]
 [6] \(A::Matrix{Int64}, B::Vector{Int64})
   @ LinearAlgebra C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\LinearAlgebra\src\generic.jl:1142
 [7] top-level scope
   @ REPL[3]:1

julia>

julia> using LinearAlgebra

julia> x = copy(b);

julia> ldiv!(qr(A), x)
3-element Vector{Float64}:
   3.0000000000000244
 -21.00000000000002
  18.0

julia> A * x
3-element Vector{Float64}:
 14.999999999999979
 14.999999999999986
 15.0

julia> A * x ≈ b
true
```

**Comment by andreasnoack** [comment]
Nothing here has changed except maybe the instruction sets used for running the examples. If the LU factorization hits an exact zero then an exception is thrown but we otherwise don't do anything about nearly singular matrices. E.g.

```julia
julia> A = [1.0 2 3; 4 5 6; 7 8 9];

julia> A[3,3] -= eps(9.0);

julia> A\b
3-element Vector{Float64}:
 -18.0
  21.0
  -3.0
```

I'm not sure we should, be this we should keep this issue open until we decide what to do.

**Comment by ViralBShah** [comment]
We now give a singluar exception. 

```
julia> A = [1 2 3;
            4 5 6;
            7 8 9];

julia> b = [15, 15, 15]
3-element Vector{Int64}:
 15
 15
 15

julia> x = A \ b
ERROR: SingularException(3)
Stacktrace:
 [1] SingularException
   @ ~/julia/usr/share/julia/stdlib/v1.9/LinearAlgebra/src/exceptions.jl:21 [inlined]
 [2] checknonsingular
   @ ~/julia/usr/share/julia/stdlib/v1.9/LinearAlgebra/src/factorization.jl:19 [inlined]
```
