### ISSUE TITLE
more general subarrays?

### ISSUE THREAD

**Issue by dfagnan** [JuliaLang/LinearAlgebra.jl#4]
I think this is an issue:

```
A=reshape(1:9,3,3)

b=ref(A,[1, 1, 3, 3, 3], [3, 2, 3, 2, 3])
5x5 Int64 Array:
 7  4  7  4  7
 7  4  7  4  7
 9  6  9  6  9
 9  6  9  6  9
 9  6  9  6  9

b=sub(A,[1, 1, 3, 3, 3], [3, 2, 3, 2, 3])
ERROR: no method sub(Array{Int64,2},Array{Int64,1},Array{Int64,1})
```

**Comment by JeffBezanson** [comment]
Right now we don't support subarrays of this kind; only range indexes.

**Comment by zahachtah** [comment]
I am not good enough programmer to make any changes myself, but it looks to me as if in Arrayviews.jl  making strides in a=1:5:100  is not that different than what making strides along a=[1 5 7 4 6 2 8] would be. I'll just put it up on the wish list, seems like view/sub(A,1:3:9) is less useful and general than view/sub(A,[1 3 9]) since you can use find(A.==x) on it. But I am immensely grateful for all the amazing work that is being done here!

**Comment by timholy** [comment]
A key point is that C libraries like LAPACK can work with "strided matrices," ones where the gap between adjacent elements is larger than 1. You can only guarantee this with Range indexes, not with general vector indexes. However, since the type of the indexes is a parameter of SubArray, it seems that in principle one might be able to combine this functionality into SubArray and dispatch based on the types of the indexes.

There is some computational efficiency that arises from having ranges (it's faster to say `r.start + i*r.step` compared to `r[i]`), and so there's some risk that we'd either be facing performance-regressions, would have to use a separate type, or would require some new technology (#5395).

Since we're still struggling a bit with how to implement efficient SubArray operations, I suspect that now is not the time to expand the scope of SubArrays. I'd recommend just copying the data for now.

**Comment by ViralBShah** [comment]
Given we are struggling to implement efficient `SubArray` operations, we should not expand this scope. Let's reopen this at a later point if necessary.
