### ISSUE TITLE
guptri request as part of linear algebra

### ISSUE THREAD

**Issue by alanedelman** [JuliaLang/LinearAlgebra.jl#5]
the other day i got a request for guptri:
http://www8.cs.umu.se/~guptri/

it's a kind of fancy schur decomposition

great if we can have it plugged in

**Comment by ViralBShah** [comment]
The webpage was last updated in 1999!

**Comment by StefanKarpinski** [comment]
Must be mature.

**Comment by andreasnoack** [comment]
and except for the mex wrapper for MATLAB the code is from 1987. Hence no LAPACK, it has its own BLAS, LINPACK and SVD solver.  However, it works fine but segfaults if I try to use vecLib or openBLAS. I have a version packaged which works like the MATLAB version according to the example on the webpage. Unfortunately it is a Mac/Linux only version because I don't know how to run the Makefile on Windows.

**Comment by ViralBShah** [comment]
We can reopen this if necessary.
