### ISSUE TITLE
Cannot construct Tridiagonal{BigFloat} and SymTridiagonal{BigFloat}

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/LinearAlgebra.jl#58]
``` julia
julia> Tridiagonal(convert(Vector{BigFloat}, randn(10)), convert(Vector{BigFloat}, randn(11)), convert(Vector{BigFloat}, randn(10))) 
ERROR: access to undefined reference
 in unsafe_copy! at array.jl:151
 in copy! at array.jl:51
 in Tridiagonal at linalg/tridiag.jl:163
 in Tridiagonal at linalg/tridiag.jl:172

julia> SymTridiagonal(convert(Vector{BigFloat}, randn(11)), convert(Vector{BigFloat}, randn(10))) 
11x11 SymTridiagonal{Float64}:
diag:  -1.85523  -1.1401  -0.779303  -0.158204  -2.33529  0.7613  0.0517818  -1.20579  0.905152  -0.163929  0.346513
 sub:  -0.302204  1.53276  0.132048  -0.210938  3.88483  0.730187  -0.936613  -0.999451  -0.905903  0.623059
```

Further issues
- The `Tridiagonal` type also includes a bunch of temporary fields which I don't think ought to belong there.
- Trying to construct `SymTridiagonal{BigFloat}` produces `SymTridiagonal{Float64} instead.

**Comment by JeffBezanson** [comment]
Instead of `copy`, `similar` or just constructing another array can be used.

**Comment by JeffBezanson** [comment]
I'm on the fence about whether `copy` should just ignore undefined entries. It would help avoid this kind of problem but could mask others.

**Comment by JeffBezanson** [comment]
The `Tridiagonal` constructors are also a bit insane in that `Tridiagonal(dl,d,du)` allocates 3 arrays and then immediately overwrites them with the arguments dl,d,du.

**Comment by jiahao** [comment]
I'm hoping to hear from folks who worked on the `Tridiagonal` codebase before touching it. The thing I want to find out about in particular is why `dutmp` and `rhstmp` are part of the `Tridiagonal` type; they seem to be used by the generic linear solver `solve!` and the matmul `mult`. Might be worth overhauling those bits.

**Comment by andreasnoack** [comment]
The tridiagonal code is pretty old. It could be written by @dmbates, but I am not sure. It was there when I started to use julia and I don't think there has been much work on the code since then. I also don't think anyone will complain if you make a major overhaul.

Btw, I have some eigenvalue related code that might fit in here, but we have to consider if we want to store elementary reflectors LAPACK style storing them in the original matrix. Also, what about constructors for symmetric tridiagonal matrices? Right now `SymTridiagonal` just uses the three central diagonals, but maybe it is more useful to construct the `SymTridiagonal` by applying elementary reflections to the matrix. Alternatively, a `SymmetricTridiagonalFactorization` (slightly long name) containing a `SymTridiagonal` matrix and a weight vector `τ` or `σ` for the reflectors.

**Comment by timholy** [comment]
I may have been the original author of Tridiagonal, way back in my first forays with Julia, but `git blame` shows it has clearly been through many hands since then. I say, clean away!

As far as temporary fields go: the intent was to allow solvers to work without allocation---people often use them along 1d "pencils" of multidimensional arrays, so you can easily end up solving 10^6 separate equations. But now that we have factorization objects, there are better ways to do this.

If you do a cleanup, here's a low-level benchmark to make sure there's no major performance regression:

```
using Grid
A = randn(10^3, 10^3);
@time interp_invert!(A, BCnan, InterpQuadratic)
```

I recognize you may even make this faster, in which case I owe you a beer.

**Comment by jiahao** [comment]
> I recognize you may even make this faster, in which case I owe you a beer.

Throw in some St Louis BBQ and you have a deal!

**Comment by timholy** [comment]
You drive a hard bargain, but...hmmm....well...OK!

(If only all my coding problems could be solved with beer and BBQ!)

**Comment by JeffBezanson** [comment]
Oops in fact I only fixed the Tridiagonal part.
