### ISSUE TITLE
qrfact(x::Number) will always throw an error

### ISSUE THREAD

**Issue by astrieanna** [JuliaLang/LinearAlgebra.jl#81]
I don't really understand what `qrfact` does, so I'm not sure how to fix this, but it definitely can't work. The problem is the second argument: `fill(x,1,1)` will always be a matrix (`Array{Number,2}`), rather than the vector that `QR` requires.

From [base/linalg/factorization.jl:300](https://github.com/JuliaLang/julia/blob/master/base/linalg/factorization.jl#L300):

``` julia
qrfact(x::Number) = QR(fill(one(x), 1, 1), fill(x, 1, 1))
```

It calls QR:

``` julia
julia> methods(QR)
JuliaLang/julia#1 method for generic function "QR":
QR{T}(factors::Array{T,2},τ::Array{T,1})
```

For example:

``` julia
julia> qrfact(2)
ERROR: no method QR{T}(Array{Int64,2}, Array{Int64,2})
 in qrfact at linalg/factorization.jl:300
```

**Comment by jiahao** [comment]
Good catch.

Option 1. I think this should simply promote `x::Number` to a 1x1 matrix instead and be done with it, i.e. just replace it with

``` julia
qrfact(x::Number) = qrfact(fill(x,1,1))
```

Option 2. Or we can force it to conform to the behavior of  `qrfact` on an actual matrix, which now returns a `QRCompactWY` instead of `QR`:

``` julia
julia> qrfact(fill(2.5,1,1))
QRCompactWY{Float64}(1x1 Array{Float64,2}:
 2.5,1x1 Array{Float64,2}:
 0.0)
```

In which case the correct method should be

``` julia
qrfact(x::Number) = QRCompactWY(fill(x,1,1), zeros(typeof(x),1,1))
```

**Comment by jiahao** [comment]
cc: @andreasnoackjensen

**Comment by andreasnoack** [comment]
I have pushed option 1 to master. I don't think it is performance critical to do QR on scalars and option 2 (and therefore also the old behaviour) doesn't work for `Complex` because the it is the convention that the diagonal in R is real. Instead of doing the calculation of the reflector it was easier to call `qrfact`. If someone has to do millions of QRs of scalars we can revisit this.

**Comment by jiahao** [comment]
I did think that option 1 was the way to go with this.
