### ISSUE TITLE
sprandbool broken

### ISSUE THREAD

**Issue by jperla** [JuliaLang/LinearAlgebra.jl#86]
some types are wrong, possibly related to c330b1d6. there are no unit tests for sprandbool

**Comment by jperla** [comment]
```
+#issue 5985                                                            
+@test sprandbool(4, 5, 0.0) == sparse(zeros(Bool, 4, 5))               
+@test sprandbool(4, 5, 1.00) == sparse(ones(Bool, 4, 5))               
+sprb45 = sprandbool(4, 5, 0.5)                                         
+@test length(sprb45) = 20                                              
+@test sum(sprb45) = 10                                                 
+                                                                       
 # issue 5853, sparse diff  
```

[pao: formatting?]

**Comment by jperla** [comment]
in test/sparse.jl.  I don't really know the fix for it, though!

**Comment by jperla** [comment]
okay i think i'll make CSC matrices store AbstractVectors

**Comment by pao** [comment]
@jperla I'm not sure what you were trying for in [this comment](https://github.com/JuliaLang/LinearAlgebra.jl/issues/86), but please try to quote code blocks, especially those which have Julia macros, since otherwise GitHub sends off notifications to users with those names (just as I did at the beginning of this comment to notify you.) Thanks!
