### ISSUE TITLE
Slow complex-real matrix products

### ISSUE THREAD

**Issue by fjarri** [JuliaLang/LinearAlgebra.jl#88]
Consider [the following benchmark](https://gist.github.com/Manticore/9340564). It compares the performance of the dot product for matrices of different sizes in Julia and in Python.

My configuration:
OSX 10.9.2
Python 3.3.4, numpy 1.8.0
Julia HEAD (as of 4 Mar 2014, commit d36bb08f63880f9428afef5a02daf964d3c2ec40), compiled with Accelerate

The results for the dot tests are (combined side-by-side for convenience)

**Python** | **Julia**

```
dot(float, float), 10 x 10: 0.08806 s | 0.029476 s
dot(float, float), 100 x 100: 0.07486 s | 0.079535 s
dot(float, float), 1000 x 1000: 0.38337 s | 0.39732 s
dot(complex, float), 10 x 10: 0.19552 s | 0.090843 s
dot(complex, float), 100 x 100: 0.16334 s | 0.57663 s
dot(complex, float), 1000 x 1000: 1.5419 s | 5.4734 s
dot(complex, complex), 10 x 10: 0.14413 s | 0.086742 s
dot(complex, complex), 100 x 100: 0.15740 s | 0.20056 s
dot(complex, complex), 1000 x 1000: 1.4927 s | 1.4955 s
```

For float-float and complex-complex products Julia and Python show similar performance (as I would expect, since they use the same linear algebra backend). But in complex-float products of sufficiently large matrices Julia is suddenly 4 times slower! Is there some float-to-complex conversion happening in the background?

**Comment by andreasnoack** [comment]
@Manticore Thank you for reporting this. I have changed your title to "matrix product" because in Julia `dot` is only used for vectors.

I can confirm your results. Actually, the problem is that there is no conversion. When two matrices have different element types then Julia uses a fall back algorithm implemented in Julia instead of promoting the real array to a complex and calling BLAS. You can try to compare

```
julia> Z=complex(randn(1000,1000),randn(1000,1000));
julia> X=randn(1000,1000);
julia> @time Z*X;
elapsed time: 2.931614198 seconds (16000336 bytes allocated)
julia> @time Z*complex(X);
elapsed time: 0.461525523 seconds (32000144 bytes allocated)
```

 As your timings show, using the Julia version might be a good idea for small matrices but not for larger.

**Comment by stevengj** [comment]
There is no need to promote the real array to complex in order to use BLAS for a dot product of vectors. In fact, you can do a BLAS dot product of a complex array Z with a real array X without making any copies or performing any conversion (assuming Z and X use the same floating-point type).

If Z and X have length N, you can just view Z as a 2xN real matrix A (the memory layouts are the same), compute b = A*X with BLAS, and then dot(Z,X) is equal to complex(b[1],b[2]).

It seems like things are not so easy with arbitrary matrix products, though.

**Comment by JeffBezanson** [comment]
related to JuliaLang/LinearAlgebra.jl#9

**Comment by andreasnoack** [comment]
The method described by @stevengj has been added in https://github.com/JuliaLang/julia/commit/da8e8ee338058b94ad83e3c705c8f620fbccb757 so the timings are now

``` julia
julia> Z=complex(randn(1000,1000),randn(1000,1000));

julia> X=randn(1000,1000);

julia> @time Z*X;
elapsed time: 0.036864228 seconds (16000448 bytes allocated)

julia> @time Z*complex(X);
elapsed time: 0.083695463 seconds (32000240 bytes allocated, 27.56% gc time)
```

The remaining cases should be covered by JuliaLang/LinearAlgebra.jl#9
